# Generated by Django 5.1.15 on 2026-02-11 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tasks", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="assigned_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assignments_made",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="assignment",
            name="assigned_to",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="task_assignments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="attachment",
            name="uploaded_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="uploaded_attachments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="comments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                help_text="User assigned to this task",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_tasks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="created_by",
            field=models.ForeignKey(
                help_text="User who created this task",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_tasks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who deleted this task",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deleted_tasks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="tasks.task",
            ),
        ),
        migrations.AddField(
            model_name="attachment",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="tasks.task",
            ),
        ),
        migrations.AddField(
            model_name="assignment",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="tasks.task",
            ),
        ),
        migrations.AddField(
            model_name="taskhistory",
            name="changed_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="taskhistory",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="history",
                to="tasks.task",
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["status"], name="tasks_status_031d4c_idx"),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["priority"], name="tasks_priorit_a9efa1_idx"),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["due_date"], name="tasks_due_dat_0359a9_idx"),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["assigned_to", "status"], name="tasks_assigne_801c9d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["created_by", "status"], name="tasks_created_87eaa0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["is_deleted"], name="tasks_is_dele_8a1818_idx"),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["-created_at"], name="tasks_created_d28591_idx"),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["task", "created_at"], name="comments_task_id_62c144_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["is_internal"], name="comments_is_inte_ba17c4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attachment",
            index=models.Index(
                fields=["task", "-uploaded_at"], name="attachments_task_id_61b1ee_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="assignment",
            index=models.Index(
                fields=["task", "-assigned_at"], name="assignments_task_id_35e7da_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="assignment",
            index=models.Index(
                fields=["assigned_to", "-assigned_at"],
                name="assignments_assigne_b3f15c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="taskhistory",
            index=models.Index(
                fields=["task", "-timestamp"], name="task_histor_task_id_b65a88_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="taskhistory",
            index=models.Index(
                fields=["-timestamp"], name="task_histor_timesta_ef1e00_idx"
            ),
        ),
    ]
