# Generated by Django 5.1.15 on 2026-02-11 12:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("task_assigned", "Task Assigned"),
                            ("task_due_soon", "Task Due Soon"),
                            ("task_overdue", "Task Overdue"),
                            ("sla_breach", "SLA Breach"),
                            ("task_approved", "Task Approved"),
                            ("task_rejected", "Task Rejected"),
                            ("task_completed", "Task Completed"),
                            ("task_closed", "Task Closed"),
                            ("comment_added", "Comment Added"),
                            ("attachment_added", "Attachment Added"),
                        ],
                        help_text="Type of notification",
                        max_length=50,
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Notification title", max_length=200),
                ),
                ("message", models.TextField(help_text="Notification message content")),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        help_text="Notification priority level",
                        max_length=20,
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the notification has been read",
                    ),
                ),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the notification was read",
                        null=True,
                    ),
                ),
                (
                    "email_sent",
                    models.BooleanField(
                        default=False, help_text="Whether email notification was sent"
                    ),
                ),
                (
                    "email_sent_at",
                    models.DateTimeField(
                        blank=True, help_text="When the email was sent", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "notification",
                "verbose_name_plural": "notifications",
                "db_table": "notifications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_assigned",
                    models.BooleanField(
                        default=True, help_text="Notify when task is assigned"
                    ),
                ),
                (
                    "task_due_soon",
                    models.BooleanField(
                        default=True,
                        help_text="Notify when task is due soon (24 hours)",
                    ),
                ),
                (
                    "task_overdue",
                    models.BooleanField(
                        default=True, help_text="Notify when task becomes overdue"
                    ),
                ),
                (
                    "sla_breach",
                    models.BooleanField(
                        default=True, help_text="Notify when SLA is breached"
                    ),
                ),
                (
                    "task_approved",
                    models.BooleanField(
                        default=True, help_text="Notify when task is approved"
                    ),
                ),
                (
                    "task_rejected",
                    models.BooleanField(
                        default=True, help_text="Notify when task is rejected"
                    ),
                ),
                (
                    "task_completed",
                    models.BooleanField(
                        default=True, help_text="Notify when task is completed"
                    ),
                ),
                (
                    "task_closed",
                    models.BooleanField(
                        default=True, help_text="Notify when task is closed"
                    ),
                ),
                (
                    "comment_added",
                    models.BooleanField(
                        default=True, help_text="Notify when comment is added to task"
                    ),
                ),
                (
                    "attachment_added",
                    models.BooleanField(
                        default=True,
                        help_text="Notify when attachment is added to task",
                    ),
                ),
                (
                    "email_frequency",
                    models.CharField(
                        choices=[
                            ("immediate", "Immediate"),
                            ("daily", "Daily Digest"),
                            ("weekly", "Weekly Digest"),
                            ("never", "Never"),
                        ],
                        default="immediate",
                        help_text="How often to send email notifications",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "notification preference",
                "verbose_name_plural": "notification preferences",
                "db_table": "notification_preferences",
            },
        ),
    ]
