# Generated by Django 5.1.15 on 2026-02-11 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("notifications", "0001_initial"),
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="attachment",
            field=models.ForeignKey(
                blank=True,
                help_text="Related attachment if applicable",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="tasks.attachment",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="comment",
            field=models.ForeignKey(
                blank=True,
                help_text="Related comment if applicable",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="tasks.comment",
            ),
        ),
    ]
