# Generated by Django 5.1.15 on 2026-04-27 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file_size',
            field=models.PositiveIntegerField(default=0, help_text='File size in bytes'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='filename',
            field=models.CharField(blank=True, default='', help_text='Original filename', max_length=255),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='mime_type',
            field=models.CharField(blank=True, default='', help_text='MIME type of the file', max_length=100),
        ),
    ]
